tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core", "https://github.com/Homebrew/homebrew-core.git"
tap "neovim/neovim"
# Archival front-end
brew "atool"
# GNU binary tools for native development
brew "binutils"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim", args: ["HEAD"]
# Swiss-army knife of markup format conversion
brew "pandoc"
# Programmatically correct mistyped console commands
brew "thefuck"
# Internet file retriever
brew "wget"
cask "font-fira-code"
cask "font-hack"
