#============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    guifont = 'Roboto Mono:h13'
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false

    # option for autocomplete
    autocomplete_method = 'ycm'
    # option for snippet
    snippet_engine = 'ultisnips'

    relativenumber = false

    # option for filetree
    filemanager = 'defx'

    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = 'complete'
auto_completion_tab_key_behavior = 'smart'

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'sudo'

# [[layers]]
# name = 'checkers'
# show_cursor_error = false

[[layers]]
name = 'format'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#c'
[layer.clang_std]
c = 'c11'
cpp = 'c++14'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#assembly'

[[layers]]
name = 'lsp'
filetypes = ['rust', 'c', 'cpp']
[layers.override_cmd]
rust = ['rls']
